language: node_js
node_js:
- '6'
deploy:
  provider: heroku
  api_key:
    secure: kU0WjYebOO1683O+5dEYWKXFKYr2Y0uZxqoWXmsY2badNETiEkW2RL23HziGWCaGZdkMD3OBtDg5NCfJwHfmGRL3W05mKWTfsFMzAt7JTLYj4y0+BtUcXjDyniO+ioSsHleL5EZZDMviVGcMxMumKhVnwHYaCLMIpLsMPF/+cs7zld/BfqWa1rnMX0OUeaOnsfwc2MkjI7/dci7vux1MhPs9zIzOonQdH70k6TWWQZgpssv23r6jzzer7W8rXyb0i0gbZcO8QnixZ7VZnoUt3pduPIkDGYmmYldAElcRgC7Qw90OST2fjv2AuDqVCZaZScaTbel5chOE6LmCckyFi9XFAwlBintk1+E3qMLhQMTEAQuvUTVGdQmULHR+eeOdc1CxT1n3OZ1bRHgCnkqv9g8ieHLXDOJy1tFPUKjJerDvuG/uy7NOT8IfsdOd8vpwJiwNyLUc4fU9JZQNVyCw+7tHint27t6x0wYjEKIa1l1e5/ED6+pURqOVZpFVxvtKZUHzxpXKe/wNQj2BbE8DwwqOkTHWk1eUnV3heP+KLoHOPjGVJqNpTjaXBhmTRwQOQYucocg/UxK5jRIq8RkpAkK2PLmuPVtwo+FClZc/ZGAElOfhvrb/C7+QcyvoKEuowIZ8UyGkpVx/L81sFyExRK+qkaUFbTaoqdtmLC+HzOc=
  app: InfrastructureApp