language: node_js
node_js:
- '6'
deploy:
  provider: heroku
  api_key:
    secure: O0fCkTStPXjB4MhzAnxwG09FPGqz2MsZ5gsSUU2QBHHbDmjV5jPKpxvOJQ3/04TnNoY7hBssc+lqkSLdSlchDSfUFmUEOSa1pbiCU3Xr0SJOnZy2/H7Lltx1jrmsH+BXYsdevb4GXo/U6uT+RitCyynDa4xRVaT1r8jAaTIu3UGpToNK2OpGmSnq00xg02ABwQIJEBDQBIvS1GxiPp+Z4z/0g3KolZ41+VSVvxS8QNZR3KgdnF6TkiaOfTpx8oxLBmsSPABlsHNLHDgyOE6D6BYnRUpPXdL4wjfsfUk9CxoK2zzAg/oJU4bDgSfmFv9dJ5Rs1bvI2OZ4dzEhiuCek3YU+Ks5SP9tvjJLvYG7saDDpidcUVZ2D/QFgFmbGTOqjIrNu6dmgYu5X5wh3QB5UkGDUB2070NZ+toqSIhO36I9NDeAwYI9KinmVF7ZOso2i/awCrlGFAVp2wMKm8g9PyCrC7nMnufY6H8avCZtjgHnWLID5WnSqpSihA8fvTJdW6lRwkYdFy1ZW2JUtOvGH4yCZHrmuMDI89uaQPkbewJ+Qu+VRD7VcoKimSj+sHHtclrmxbqI5xmMgple32WvqTD18Y7pDa7ZEXyb8jvwlM4D4WPKBRCvjc/EcJGUin+Qga/N1q59AY7FS84tSrhb1BC7xWJwTSu6LZBYfhZKP9A=
  app: dz-infrastructure
  on:
    repo: Solechko/dz_infrastructure
