language: node_js
node_js:
- '6'
deploy:
  provider: heroku
  api_key:
    secure: Ll2mtnYPd66Zm8MnDzhIK/ucB3fyZdp0RwQcr/r6TD/OtGi599RKLYHMmxvQ3PLFZr7o3dosw5s8kTpWDbzj9DTzfGgmLuwJKLy6oBbb2Ektx+0UsHnNyo5QMGkKBD7Y1zVl+qlD4EzM7Z88F4Rlm1vI+RdVhyvwYU6x7Jw88HWsFwP2fyL10DW2+PwBxoIOyKOqU/ZiI5W/CFkSK6kIJ8b7/Ydyj0JD2MmGWlYpV+WEka/SZIDKXcHn46zuoQ9/PzFrip+qeWhgDejtX31FWuLlC0lfwUArCD0VlE1Oi+ijBSks8dae0MA/5voYmkpP5JeNeH+b7sasvGyTJZNqM2muFFjC9ry9ynhiiMTJClsrBfw+slokOcHvc4SSGk5GZcGb3z7O4foarYYPJ6a13BL+WHgrID8VBb+9fpBnCdP+AVNrg94IVhspstzARm3u8zLcZG8HblRSLcOVRqNXxW/uh4dss9mpi55ojVIaAm38vsrobmpZOSp+Q9O7HwC6lk2HbmRQ92hBtZvparAj2eJqDBLUOIC4ZMOIdnWJgmJDXA8k5QEZ6/HiOr36uoJHAWEcBAdFJvtB6ocU34LaQ4z+eDwwKat3itqYw1RZGbX8o7Q5QpA3RMJ0cqx4STdKm3OdWuS6Px1s72jLZnoXWVKmw4ST3sZwR//IKCO55rc=
  app: dz_infrastructure
  on:
    repo: Solechko/dz_infrastructure
