language: node_js
node_js:
- '6'
deploy:
  provider: heroku
  api_key:
    secure: bccH5HGhEir4DbJIoVoqMsFmCgNtKfSBPO55UwWkxxx+akGoM/jPmcvN46W1rXIauhtDHMbDvZrNevLnjCh/1QFqveQZjtTpNA/pMvAJFt3ODLji81/gs0akShie69F7X3yz2SoBIIC4jNyOxCrdj1jF8X6+my+bQw2O5rhABvx0+JpLUCUrg4gFf1Y4M+5QYsOYOX46yPWrGt6162YkrewqM1+OPUg0kNsV4JwK+ouOcResYCniHmZ5zgv+6/PW/QaZop+PBuz5ksEk+a4hZ26+KTpfa22v4tvP6eXuBL+qbPIxYbL7gSwDE+wJZ4HO/yTYuluIAhNMSQ2RqjpgMmD/J+4eF+Qm77qmzTWfYVRNQ3piaz44FhhEKhX/17u2K/ybTkD+V/mD++axvNHMcCRhHIg+Eod/Vo4o6SIQHSKV5+238QeCqB12B/ndlu6BqWcR1PZB3Z8Cc2PozFodpgcsuFJpZLlOgOdkOdYX5t6BjUU//a5DyfNRG9vvSOisdKyk60Acr60a48x5MnHBdDbsuRp1JOXtZsMzKYs8BrG4aoQHndBdunkosrHwfsGUF7klm88OUuNVXHfkK5TVJ8Et6ywT37DhQCd2iJWc4MYcmx5JP9kwB6zN7WeQCxhEYisRnjUIBEj9epRsVdPnwxH1hgypZ5c71HR7GDeCHWY=
  app: dz_infrastructure
  on:
    repo: Solechko/dz_infrastructure
